FROM node:10.15.0

# Create app dicectory in container
RUN mkdir -p /srv/app/todo-server
WORKDIR /srv/app/todo-server 

COPY package.json /srv/app/todo-server
COPY package-lock.json /srv/app/todo-server

RUN npm install

COPY . /srv/app/todo-server

CMD ["node" , "index.js"]